image: ghcr.io/cognvn/gitpod-workspace:android-sdk
tasks:
- init: |
    chmod +x ./android/gradlew
    yarn install
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - vscjava.vscode-java-pack
    - https://github.com/microsoft/vscode-react-native/releases/download/1.9.1/vscode-react-native-1.9.1.vsix
    - https://github.com/microsoft/vscode-gradle/releases/download/3.11.0/vscjava.vscode-gradle-3.11.0.vsix