name: Build ggml-cuda 13
on:
  workflow_dispatch:
    inputs:
      cuda_ver:
        description: "Cuda version"
        required: true
        default: "13.0.2"
      cuda_packages:
        description: "Cuda packages"
        required: false
        default: '["nvcc","nvrtc","nvtx","cuda_profiler_api","cudart","visual_studio_integration"]
        
jobs:
  build_ggml_cuda:
    runs-on: windows-2025
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v6
        with:
          repository: ggml-org/llama.cpp
          branch: main

      - name: Install ccache
        uses: ggml-org/ccache-action@v1.2.16
        with:
          key: windows-cuda-13.0
          variant: ccache
          evict-old-files: 1d

      - name: Install Cuda Toolkit
        uses: Jimver/cuda-toolkit@master
        with:
          cuda: "${{ github.event.inputs.cuda_ver }}"
          method: network
          sub-packages: "${{ github.event.inputs.cuda_packages }}"
          non-cuda-sub-packages: '["libcublas"]'

      - name: Install Ninja
        id: install_ninja
        run: |
          choco install ninja

      - name: Build
        id: cmake_build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -S . -B build -G "Ninja Multi-Config" ^
            -DGGML_BACKEND_DL=ON ^
            -DGGML_NATIVE=OFF ^
            -DGGML_CPU=OFF ^
            -DGGML_CUDA=ON ^
            -DLLAMA_CURL=OFF
          set /A NINJA_JOBS=%NUMBER_OF_PROCESSORS%-1
          cmake --build build --config Release -j %NINJA_JOBS% --target ggml-cuda

      - name: Pack artifacts
        id: pack_artifacts
        run: |
          7z a llama-bin-win-cuda-13.0-x64.zip .\build\bin\Release\ggml-cuda.dll

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          path: llama-bin-win-cuda-13.0-x64.zip
          name: llama-bin-win-cuda-13.0-x64.zip
