name: Build WSL kernel
on:
  workflow_dispatch:
    inputs:
      kernel_ver:
        description: 'Kernel version'
        require: true
        default: 'linux-msft-wsl-5.15.62.1'

jobs:
  build_win:
    name: Build WSL kernel
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout WSL2 kernel
        uses: actions/checkout@v3
        with:
          repository: microsoft/WSL2-Linux-Kernel
          ref: ${{ github.event.inputs.kernel_ver }}
                
      - name: Install dep
        run: |
             sudo apt-get update
             sudo apt install build-essential flex bison dwarves libssl-dev libelf-dev -y
          
      - name: Build kernel
        run: make KCONFIG_CONFIG=Microsoft/config-wsl

      - name: Upload kernel
        uses: actions/upload-artifact@v2
        with:
          name: tesseract-${{ matrix.config.arch }}
          path: arch/x86/boot/bzImage
