name: Build WSL kernel
on:
  workflow_dispatch:
    inputs:
      kernel_ver:
        description: 'Kernel version'
        required: true
        default: 'linux-msft-wsl-6.6.36.6'

jobs:
  build_win:
    name: Build WSL kernel
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout WSL2 kernel
        uses: actions/checkout@v4
        with:
          repository: microsoft/WSL2-Linux-Kernel
          ref: ${{ github.event.inputs.kernel_ver }}
                
      - name: Install dep
        run: |
            sudo apt-get update
            sudo apt install build-essential flex bison libssl-dev libelf-dev bc python3 pahole cpio -y
          
      - name: Build kernel
        run: |
            make -j$(nproc) KCONFIG_CONFIG=Microsoft/config-wsl
            make INSTALL_MOD_PATH="$PWD/modules" INSTALL_HDR_PATH="$PWD/headers" modules_install headers_install
            
      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: bzImage
          path: arch/x86/boot/bzImage
